<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_entity_view_alter().
 */
function submission_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() == 'event') {
    if ($build['#view_mode'] == 'full') {
      $build['submission_link'] = [
        '#type' => 'link',
        '#title' => t('Subscribe'),
        '#url' => Url::fromRoute('submission.add_form', ['event' => $entity->id()]),
        '#options' => [
          'attributes' => [
            'class' => ['use-ajax'],
            'data-dialog-type' => 'modal',
            'data-dialog-options' => Json::encode([
              'width' => 700,
            ]),
          ]
        ],
        '#attached' => ['library' => ['core/drupal.dialog.ajax']],
        '#weight' => 100,
      ];
    }
  }
}
